on:
  push: 
    branches: [main]


jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
        - name: Building Frontend for simulation
          uses: actions/checkout@v3
        - run: npm run build react_native
        - run: npm run build react_web       
